### ISSUE TITLE
Running in VPC namespace

### ISSUE THREAD

**Issue by rakshasa-1729** [sethvargo/vault-on-gke#12]
**Question**
How to run it alongside other applications in different namespaces in a different namespace  within  a VPC?

**Considerations**
I currently use it as a service with cluster IP and the vault fails to init and unseal.

**Comment by sethvargo** [comment]
Hey @PrahathessRaghavan 

I've done some thinking about this and also socialized with some folks internally. Our recommendation is that you should have a dedicated cluster for Vault and always communicate through the load balancer.

**Comment by PrahathessRengasamy** [comment]
@sethvargo thank you for getting back It'll be much useful learning for me if you can share why that's is so , if this is not a big ask .
Thanks

**Comment by sethvargo** [comment]
A lot of it revolves around TLS and upgrades. By using the load balancer, you don't have to trust all possible IPs and DNS addresses. It also helps because you can swap clusters out to do upgrades more easily.
