### ISSUE TITLE
Good idea to have GCS bucket versioning enabled without a lifecycle policy?

### ISSUE THREAD

**Issue by RobinsonWM** [sethvargo/vault-on-gke#13]
This guide has been immensely helpful to me.  I didn't apply it verbatim, but I used it as a reference.

**Question**

While destroying and recreating the configuration, I noticed that my GCS bucket was taking a very long time to delete.  Using `gsutil ls -a` showed I had accumulated countless generations of the `core/lock` file.  Would it be a good idea to disable versioning on the GCS bucket or add a `lifecycle_rule` to prevent too many old generations of that file from piling up?

**Comment by sethvargo** [comment]
Yea... That's a pretty good idea, considering how that file gets generated every 15s or so... Updating now.
