### ISSUE TITLE
Error for roles/resourcemanager.projectCreator even with service account: Project Owner

### ISSUE THREAD

**Issue by todd-dsm** [sethvargo/vault-on-gke#16]
**Question**
GCP nube experimenting with this deployment method. 

Running the terraform bit, as a single user with a vanilla account - not associated with a company(org_id, billing_account, etc), and it seems to have an issue with creating the project even though the vault service account is assigned `project -> owner`. 

Does Terraform need credentials that authorize it to create projects?

Whatever it is, I'm pretty sure I'm thinking about this wrong.

```
Error: Error applying plan:

1 error(s) occurred:

* google_project.vault: 1 error(s) occurred:

* google_project.vault: error creating project vault-aca224e779e3bb17 (vault-aca224e779e3bb17): 
googleapi: Error 403: User is not authorized., forbidden. If you received a 403 error, make sure you
have the `roles/resourcemanager.projectCreator` permission
...
```

![image](https://user-images.githubusercontent.com/2463935/47168512-f2401680-d2b5-11e8-85bf-896c394e23e8.png)

**Considerations**
Afterward, went through the process of setting up an organization to establish the org_id, billing_account, et al., then auth'd as a new, authorized user; same result.

**Comment by sethvargo** [comment]
Hi @todd-dsm 

Do you have [gcloud installed](https://cloud.google.com/sdk/gcloud/)? By default, this will pull your application default credentials. How are you supplying credentials to Terraform? https://www.terraform.io/docs/providers/google/getting_started.html#adding-credentials

**Comment by brettcurtis** [comment]
@todd-dsm - Maybe I can help here too, looks like your image shows project/owner. What you need here is:
![image](https://user-images.githubusercontent.com/1610100/47178645-d6566800-d2e9-11e8-9029-3281b11552e9.png)

**Comment by todd-dsm** [comment]
@sethvargo Everything seems to be installed:
```
$ gcloud projects list 
PROJECT_ID            NAME              PROJECT_NUMBER
abiding-envoy-XOXOXO  My First Project  XOXOXOXOXO
vault-service-XOXOXO  vault-service     XOXOXOXOXO

$ gcloud config list 
[core]
account = user@domain.tld
disable_usage_reporting = True
project = abiding-envoy <-- default project as suggested in the README.

Your active configuration is: [default]
```

@brettcurtis my assumption was that Project Owner was all-encompassing.
https://cloud.google.com/resource-manager/docs/access-control-proj#using_predefined_roles

But I sure can give it a try.

**Comment by todd-dsm** [comment]
@sethvargo as suggested, generated a new terraform service account and downloaded the json file. Exported it and sourced it in; still no luck. I've got more reading to do.

**Comment by sethvargo** [comment]
Hmm that's a bit odd. I just tried with my personal gmail account and it worked fine. Could it be a billing issue? Are you on a free trial? If so, could you try adding a billing account just to diagnose if that's the issue?

**Comment by brettcurtis** [comment]
@todd-dsm - you mentioned you created an org. You will need both the role i listed above as well as billing user set at the org level (not project) for the user or service account you're running terraform as. I think that will get you working.

**Comment by todd-dsm** [comment]
> Hmm that's a bit odd. I just tried with my personal gmail account and it worked fine. Could it be a billing issue? Are you on a free trial? If so, could you try adding a billing account just to diagnose if that's the issue?

@sethvargo the account was free when I set it up in 2014 or whenever but it's billing now. I did add myself as the billing admin, that wasn't explicitly configured. I'm `voidSurfr` on gcp/slack.

**Comment by todd-dsm** [comment]
> @todd-dsm - you mentioned you created an org. You will need both the role i listed above as well as billing user set at the org level (not project) for the user or service account you're running terraform as. I think that will get you working.

@brettcurtis I did create an org, out of frustration but I really don't want it. I'd rather burn down the personal account and reinitialize it in the case there are 2014 boogers floating around the backend and keep my life simple. 

If I can't do that, I'll diddle with the organization.

**Comment by todd-dsm** [comment]
> @todd-dsm - Maybe I can help here too, looks like your image shows project/owner. 

@brettcurtis _Resource Manager > Project Creator_ isn't an option in either (personal/organization) account type.
![image](https://user-images.githubusercontent.com/2463935/47235447-ede72c80-d38d-11e8-8766-fa405075f25e.png)

**Comment by sethvargo** [comment]
Hey @todd-dsm - if you're the account owner, you're the billing owner. You shouldn't need an org to make these things work, but I'm also struggling to reproduce this on my personal account. If it's not too much trouble, could you create a throw-away Gmail account (personal) and see if it happens on a fresh account?

**Comment by todd-dsm** [comment]
@sethvargo I can totally do that but - I dug enough and found the [provider says]:

> Projects created with this resource must be associated with an Organization

I should have started testing at the top; my bad. Still want to test?

 

[provider says]: https://www.terraform.io/docs/providers/google/r/google_project.html

**Comment by todd-dsm** [comment]
@sethvargo abandoned the personal account and started back with Organization. Just to test, I created a few to see if my (human) user account has the access:

```
$ gcloud projects create vault-0d8f7704fb19fd02
Create in progress for [https://cloudresourcemanager.googleapis.com/v1/projects/vault-0d8f7704fb19fd02].
Waiting for [operations/cp.8704500116594212195] to finish...done.                                                                       

$ gcloud projects list
PROJECT_ID              NAME                    PROJECT_NUMBER
abiding-envoy-219722    My First Project        814249614774
vault-0d8f7704fb19fd02  vault-0d8f7704fb19fd02  347170339726
```

confirmed

---
There is still some funk though. I'm still not able to either:

Empower the terraform service account:
```
grep GOOGLE ~/.bashrc 
export GOOGLE_APPLICATION_CREDENTIALS="$HOME/.config/gcloud/terraform-abiding-envoy.json"
```

 or Application Default Credentials? 

Still unclear on the foundational assumptions the terraform code is making or how to solve for it.

**Comment by todd-dsm** [comment]
2 new points of interest:

1. As suggested, created a throw-away account; same issue.
I'm not sure how you were able to generate a new account and it just worked. Still scratching my head on that. 

2. At the Orgaizational level, worked through a community write-up for creating Terraform Admin Project and fixed the broken parts. This is [what it takes] to get going.

If it can work in an individual account, I'll post the process; the `google_kms_key_ring` makes it difficult though.

closing issue

[what it takes]: https://github.com/todd-dsm/gcp-tf-admin-setup
