### ISSUE TITLE
additional scripts

### ISSUE THREAD

**Issue by awolde** [sethvargo/vault-on-gke#18]
**Question**
So @sethvargo where the bash scripts at from the presentation you did on Google Next 2018 :)

**Comment by sethvargo** [comment]
Which scripts exactly? https://github.com/sethvargo/vault-kubernetes-workshop

**Comment by awolde** [comment]
The same repo. You had `scripts/setup-comms.sh` in the video (https://www.youtube.com/watch?v=B16YTeSs1hI) and couple of others for setting up a simple app.

**Comment by sethvargo** [comment]
Yea - they are in the repo I linked above
