### ISSUE TITLE
Replace shellout to kubectl with kubernetes_stateful_set

### ISSUE THREAD

**Issue by RobinsonWM** [sethvargo/vault-on-gke#19]
Today terraform-provider-kubernetes 1.4 was released with support for [kubernetes_stateful_set](https://www.terraform.io/docs/providers/kubernetes/r/stateful_set.html), so the example can likely be updated to use the new resource instead of shelling out to `kubectl`.

The readme has this text at the bottom:
> Q: Why didn't you use the Terraform Kubernetes provider to create the pods? There's this hacky template_file data source instead... 
> A: StatefulSets are not supported in Terraform yet. Should that change, we can avoid the shellout to kubectl.

**Comment by sethvargo** [comment]
Yea [I saw it landed in master](https://twitter.com/sethvargo/status/1067848524027568129). Wasn't aware it was released yet though!

**Comment by sethvargo** [comment]
I got it working, but sadly [affinity is not yet supported](https://github.com/terraform-providers/terraform-provider-kubernetes/issues/233). I'm going to open the PR, but it will have to wait until that lands.

**Comment by bgeesaman** [comment]
@sethvargo [There was a recent update](https://github.com/terraform-providers/terraform-provider-kubernetes/issues/233) that seems to indicate it landed?
Edit: That might be an erroneous statement.

**Comment by sethvargo** [comment]
It doesn't seem to be in a released version yet

**Comment by regner** [comment]
Just going through attempting to convert our fork of this over to using Terraform for the stateful set and have run into a few issues:

1) The service config option externalTrafficPolicy is not supported (https://github.com/terraform-providers/terraform-provider-kubernetes/pull/59)
2) The affinity config option on the pod spec if not currently supported (https://github.com/terraform-providers/terraform-provider-kubernetes/issues/233)

**Comment by sethvargo** [comment]
Done!
