### ISSUE TITLE
Initializing vault on an existing cluster

### ISSUE THREAD

**Issue by jeroenrinzema** [sethvargo/vault-on-gke#26]
I am trying to modify the terraform scripts in a way that i am able to initialize vault on an existing kubernetes cluster. I managed to deploy the whole project, but am getting stuck on the following error message:

```
2018-12-23T20:15:38.750Z [ERROR] core: failed to store keys: error="failed to encrypt keys for storage: googleapi: Error 403: Permission 'cloudkms.cryptoKeyVersions.useToEncrypt' denied for resource 'projects/xxx/locations/europe-west3/keyRings/vault/cryptoKeys/vault-init'., forbidden"
```

where `xxx` contains the project name. When initializing the kubernetes cluster do i create a service account. Could it be that i have to give the service account secret key somewhere to vault for it to be able to authenticate?

**Comment by rakshasa-1729** [comment]
I believe you need to add the cloudkms.cryptoKeyVersions.useToEncrypt permissions to the kubernetes default service account  or the GCP IAM service account vault is using .
```
resource "google_kms_crypto_key_iam_member" "vault-init" {
  count         = "${length(var.kms_crypto_key_roles)}"
  crypto_key_id = "${google_kms_crypto_key.vault-init.id}"
  role          = "${element(var.kms_crypto_key_roles, count.index)}"
  member        = "serviceAccount:${google_service_account.vault-server.email}" //replace this with your service account email
}
```

**Comment by jeroenrinzema** [comment]
@PrahathessRaghavan thank you for the quick reply. I am trying to set the `cloudkms.cryptoKeyVersions.useToEncrypt` role for the `google_kms_crypto_key_iam_member`.

```terraform
# Grant service account access to the key
resource "google_kms_crypto_key_iam_member" "vault-init" {
  count         = "${length(var.kms_crypto_key_roles)}"
  crypto_key_id = "${google_kms_crypto_key.vault-init.id}"
  role          = "${element(var.kms_crypto_key_roles, count.index)}"
  member        = "serviceAccount:${google_service_account.vault-server.email}"
}
```

```terraform
variable "kms_crypto_key_roles" {
  type = "list"

  default = [
    "roles/cloudkms.cryptoKeyEncrypterDecrypter",
  ]
}
```

Could it be something else?

**Comment by jeroenrinzema** [comment]
I did not resolve the issue and decide to run vault completely on it's own cluster
