### ISSUE TITLE
Vault Upgrade

### ISSUE THREAD

**Issue by MaxDiOrio** [sethvargo/vault-on-gke#27]
We used your Terraform script to deploy vault to GKE and it worked great.  That was Vault version 0.11.1.   Now that Vault 1.0.1 is out, what is the process to upgrade the vault version?  I don't want to blow anything up in the existing environment, even if it's not in true production mode yet.

Thanks.

**Comment by sethvargo** [comment]
Update the vault_version variable and re-apply
