### ISSUE TITLE
Add securityContext

### ISSUE THREAD

**Issue by Kaisle** [sethvargo/vault-on-gke#28]
**Describe the feature you'd like**
We should drop all AppArmor capabilities except for IPC_LOCK, and set allowPrivilegeEscalation and privileged to false. This is all Vault needs to run.

**Describe alternatives you've considered**
Unless there is a way to make these changes not apply to the entrypoint, the change would require the creation of a custom entrypoint, as the entrypoint needs the CHOWN and SETFCAP capabilities. 

Perhaps you could bypass the CHOWN requirements by mounting /vault/file and /vault/logs as volumes with the correct permissions but what about m_lock? 

m_lock requires the following call:

`setcap cap_ipc_lock=+ep $(readlink -f $(which vault))`

Of course you could just set the SKIP_SETCAP env to false and it will ignore this step but then there is no m_lock. 

What's your take on this?

**Comment by sethvargo** [comment]
I guess my take is... you should raise these issues with the HashiCorp team and ask them to reduce the permissions in the entrypoint?

**Comment by Kaisle** [comment]
Thank you, I will raise an issue there.

However, I just learned that there is no support for memory swapping on Kubernetes. Can you confirm that this is true?

If true, it would be make little sense to enable m_lock. Great news, because then we can run without SETFCAP. If you are interested, I can submit a PR that will add a securityContext with only the SETUID and SETGID capabilities enabled. It will also disallow privilege escalation. I like the fact that you already isolate Vault in its own project. This will improve security even further.

**Comment by sethvargo** [comment]
> I just learned that there is no support for memory swapping on Kubernetes 

Do you have a reference for that?

**Comment by Kaisle** [comment]
See this issue: https://github.com/kubernetes/kubernetes/issues/53533

Also: https://serverfault.com/questions/881517/why-disable-swap-on-kubernetes

I was very surprised when I learnt this.

**Comment by sethvargo** [comment]
If I'm reading that issue correctly, it seems that there's hacky workarounds to enable swap, and the issue is _open_ indicating it might be supported in the future. For that reason, I still think it's a best practice to give mlock cap
