### ISSUE TITLE
Vault No such host

### ISSUE THREAD

**Issue by MaxDiOrio** [sethvargo/vault-on-gke#34]
We've been using Vault in GKE for a month or so now and it's been working well.  Today, I went to test a few things and started getting I/o timeouts using the vault cli.

In the Container logs for vault-1:

[ERROR] core: error during forwarded RPC request: error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup $(POD_IP_ADDR): no such host""

[ERROR] core: forward request error: error="error during forwarding RPC request"

vault-0 pod doesn't show any issues in the logs.

I killed vault-1 and it re-created with the same errors in the logs.  Is there something I'm missing given that nothing in the environment has changed since Vault was turned up?  

If I log into the container and view the environment:
POD_IP_ADDR=10.8.0.18
cluster_addr = "https://$(POD_IP_ADDR):8201"

Makes it seem like it's getting the pod IP ok.  10.8.0.18 is the vault-1 vault pod container IP.  I can ping it just fine from the console.

Doing a netstat from the console doesn't show it listening on 8201 though.

Doing the same thing from vault-0 shows it is listening on 8201.

This makes sense since 8201 should only be on the active node.  But why am I getting these errors in the log, and why all of a sudden getting I/o timeouts connecting to vault remotely?

Thanks.

**Comment by sethvargo** [comment]
Hi @MaxDiOrio 

Thanks for opening an issue. This looks like it might be an upstream issue with Vault, because I don't see anything in here specific to Kubernetes or GKE. Have you opened an issue there?

**Comment by MaxDiOrio** [comment]
I haven't.  Wasn't sure if it was something specific to Google Cloud given the $(POD_IP_ADDR) is a Google thing.  It's also always been shockingly slow.  A vault login can take 10-20 seconds to log in.  That just doesn't seem right at all.  Feels like something may be wrong with the google load balancer.

**Comment by sethvargo** [comment]
Hi @MaxDiOrio 

`$(POD_IP_ADDR)` is a Kubernetes thing, not a Google thing. What do they Vault logs show?

**Comment by MaxDiOrio** [comment]
If I do the following to go directly to the app (connects to vault-0, it works flawlessly.  It's fast, no time outs, etc.:
gcloud container clusters get-credentials vault --region us-central1 --project vault-227419 \
 && kubectl port-forward $(kubectl get pod --selector="app=vault" --output jsonpath='{.items[0].metadata.name}') 8080:8200

If I force it to go to vault-1 pod, I get the same rpc errors from vault-1, but doing a vault read secret/test returns data from vault-0 successfully and the connection is still fast.

It's only when I access it through the Google TCP load balancer/public IP does it get flaky with timeouts client side. 

The vault logs are in the original post - I can't find any additional log entries being output anywhere, including the vault machine itself.  The following is being logged over and over - any time a connection to vault-1 is made:

2019-01-30T17:07:37.376Z [ERROR] core: error during forwarded RPC request: error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup $(POD_IP_ADDR): no such host""
2019-01-30T17:07:37.376Z [ERROR] core: forward request error: error="error during forwarding RPC request"

**Comment by MaxDiOrio** [comment]
Should line 100 in the vault.yaml be braces or parens?

cluster_addr = "https://$(POD_IP_ADDR):8201"

Given that the error references this exactly, it seems like it's not being replaced with the value of POD_IP_ADDR at all.

**Comment by sethvargo** [comment]
> Should line 100 in the vault.yaml be braces or parens?

Parens - that's [read by Kubernetes at runtime](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/). The things in curly braces are interpolated by Terraform _before_ submission.

Did you accidentally remove [the environment declaration above](https://github.com/sethvargo/vault-on-gke/blob/ca43496b14e960b1ed9ffc8e421988b78a4719fa/k8s/vault.yaml#L93-L96)?

**Comment by MaxDiOrio** [comment]
No - the declaration is there.  But it's not injecting the actual pod ip there.

Here's the live YAML from the GKE Console:

```
  - args:
    - server
    env:
    - name: VAULT_LOCAL_CONFIG
      value: |-
        api_addr     = "https://actualPublicIP"
        cluster_addr = "https://$(POD_IP_ADDR):8201"

        ui = true

        seal "gcpckms" {
          project    = "vault"
          region     = "us-central1"
          key_ring   = "vault"
          crypto_key = "vault-init"
        }

        storage "gcs" {
          bucket     = "vault-storage"
          ha_enabled = "true"
        }

        listener "tcp" {
          address       = "0.0.0.0:8200"
          tls_cert_file = "/etc/vault/tls/vault.crt"
          tls_key_file  = "/etc/vault/tls/vault.key"
          x_forwarded_for_hop_skips = 2
          tls_disable_client_certs = true
        }
    - name: POD_IP_ADDR
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
```

**Comment by MaxDiOrio** [comment]
Not sure if order matters here.  But in the terraform yaml file, the env declaration is above the VAULT_LOCAL_CONFIG, but when it actually created the yaml in GKE, it puts the declaration below the VAULT_LOCAL_CONFIG.

**Comment by MaxDiOrio** [comment]
![image](https://user-images.githubusercontent.com/25855524/52015451-00562380-24b0-11e9-80a5-33134c134658.png)

**Comment by sethvargo** [comment]
Can you post your full YAML in a [Gist](gist.github.com)? Something weird is going on - I just tested it and $(POD_IP_ADDR) is correctly interpolated as 10.x.y.z for me.

**Comment by MaxDiOrio** [comment]
This (the timeouts) really feels like it's GKE Load Balancer related too.  I changed the load balancer to expose 8200 as well as 443, and I'm actually getting slightly faster performance on 8200.  It does return responses, but maybe 50% of the time.   443 is still only working one out of 100 attempts.

Eh - it's gone down the tubes - neither port is responding well again.

Also - I'm using Vault 1.0.2 (upgraded from 1.0.1 today).  

Here's the YAML that GKE shows when looking at the deployed stateful set:
https://gist.github.com/MaxDiOrio/879d81604f7d174dccf9cf99cad5ef17

Here's the YAML used via Terraform:
https://gist.github.com/MaxDiOrio/6a72757f28606f7949c492db2f14c983

**Comment by MaxDiOrio** [comment]
So I tried changing the Load Balancer ExternalTrafficPolicy back to Cluster (from local, that we changed it to to get the true source IP address to show up in the logs.

Accessing vault via 443 is back to slow (30+ seconds), but responding.
Accessing vault via 8200 is fast and responding fine.

**Comment by sethvargo** [comment]
cluster_addr needs to be `"https://$(POD_IP_ADDR):8201"` not `"https://$POD_IP_ADDR:8201"` (note the parenthesis). 

I haven't tested with Vault 1.0.2 yet, so it's possible something is happening there. I'd be curious if it reproduces on 1.0.1.

The port for the load balancer won't matter, unless there's something on your corporate network with outbound access.

**Comment by MaxDiOrio** [comment]
I changed it back and it is now working again.  Which is strange because you can see from my first few posts that the string was correct and it still wasn't working.  I changed it along the way to other values to test a few things out.

I have the time out issue only through the load balancer.  I've tried on 4 different computers and 3 different internet connections.  This morning it was working fine for an hour or two.  Now it's back to timing out.  When when timing out over the internet, the kubectl port forwarded connection works 100% of the time.

**Comment by MaxDiOrio** [comment]
I wonder if we're running into the following:

Because of the way high availability works in vault, if the balancer redirects to a standby instance and it redirects to the balancer again, you could enter an infinite redirection loop.

Sometimes it hits the active node and works sometimes it hits the standby node, gets redirects back to the external IP, and back to the secondary node?

I'm not sure we can use a health check here to use the Vault health check API and only consider the active node in the load.  

Maybe switching over to an HTTP load balancer would be better due to the expanded health check abilities?

**Comment by tceduard** [comment]
Hi @MaxDiOrio, @sethvargo  I've been following this thread and I am seeing the same results as you just described above. From my research I arrived at the conclusion that the request may be routed to a secondary node which then sends it back to the load balancer which may send it to the active node.  [HA vault documentation](https://www.vaultproject.io/docs/concepts/ha.html#behind-load-balancers)

This would explain the symptoms of why some requests are answered fast and some are answered slow.

**Comment by sethvargo** [comment]
So would you recommendation be to remove `?standbyok` from the heath check, removing the standbys from the LB?

**Comment by MaxDiOrio** [comment]
Just tested that out and it doesn't change a thing.  Still getting time outs.

**Comment by MaxDiOrio** [comment]
I created a Google internal load balancer and that works flawlessly as well.  It really is an issue solely with the TCP Network Load Balancer.

**Comment by sethvargo** [comment]
I'm not really able to reproduce this, sorry. Have you tried a different region? I usually run in us-east1 or 4

**Comment by MaxDiOrio** [comment]
Really don't have the option to set up an entirely new environment.  We run all our services in us-central1

**Comment by tceduard** [comment]
hi! I am based in UK so I was running vault in europe-west2. I've created another cluster in us-central1 and these are some measurements of how fast are the responses to the `vault status` command

us-central1 | HA mode |-| europe-west2 | HA mode
-|-|-|-|-
real 0m0.736s | standby |-| real 0m0.528s | standby
real 0m0.829s | standby |-| real 0m0.505s | standby
real 0m0.830s | standby |-| real 0m0.111s | active
real 0m1.073s | active |-| real 0m0.093s | active
real 0m0.858s | standby |-| real 0m0.511s | standby
real 0m0.797s | active |-| real 0m0.570s | standby
real 0m0.842s | standby |-| real 0m0.503s | standby
real 0m0.950s | active |-| real 0m0.104s | active

As you can see the difference in response times for the active vs standby on the US side are fairly small in comparison to the same thing observed in EU.

**Comment by sethvargo** [comment]
@eduard-t thanks for those numbers. There's a variety of factors that could cause that, but I'll pass them along to the team. In all cases though, you're not seeing the 30s+ time that @MaxDiOrio is reporting. I agree that 1s+ RTT isn't ideal, but it's orders of magnitude lower than what was previously reported.

**Comment by tceduard** [comment]
thank you!

**Comment by MaxDiOrio** [comment]
@eduard-t - at least you're making connections.  I'd be very happy with a 0.5s response time.  I'm getting about 95% time outs.

If I curl the Vault health endpoint, it returns in 0.248s
If I then try to read a secret over port 443 immediately after, it's 30.531s 
If I try to read a secret from 8200, 0.183s

On the internal load balancer, I'm actually seeing the exact same pattern:

Port 8200:  0.18s to the active node every single time.
Port 443:    30.322s to the active node.

I have no idea why there is a difference between 8200 and 443, other than the proxying to the back end.

The other thing I've noticed is that setting the ExternalTrafficPolicy to Cluster on the Load Balancer service allows traffic to consistently pass on 443, albeit slowly.  Setting it to Local causes timeouts.
