### ISSUE TITLE
consul back end adition

### ISSUE THREAD

**Issue by vdamianchicon** [sethvargo/vault-on-gke#39]
**Question**
What is your question?
Can you pleas add a consul back end option as part of this deployment please?
**Considerations**
Are there any other considerations?
The Hashicorp supported and recommended deployment includes Consul
Disaster Recovery on a corrupted GS Back end using the opensource version can be challenging.

**Comment by sethvargo** [comment]
You can edit the vault.yaml template to use any storage backend you'd like. This is specific to GCP and I don't want to introduce another dependency.
