### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by uasaigoli** [sethvargo/vault-on-gke#4]
I am using existing project (my-project).

In terraform files I have done the following:
1.  used following in the variables.tf
variable "project" {
  type    = "string"
  default = "my-project"
}
2. replaced ${google_project.vault.project_id} to ${var.project} in all the *.tf

3. Received following error with > terraform apply

* google_service_account_key.vault: Error creating service account key: googleapi: Error 403: Permission iam.serviceAccountKeys.create is required to perform this operation on service account projects/my-project/serviceAccounts/vault-server@my-project.iam.gserviceaccount.com., forbidden

do I need add any lines to have right permission ?

**Comment by sethvargo** [comment]
Hi @uasaigoli 

How are you authenticating to Terraform? Did you run `gcloud auth application-default login` or generate a dedicated service account? You can read more here: https://www.terraform.io/docs/providers/google/index.html#configuration-reference

**Comment by uasaigoli** [comment]
Thanks @sethvargo and appreciate your response. This is an awesome project.

I have used `gcloud auth login` and used my G suite account. 

It looks like my G Suite account needs to have a certain permission - iam.serviceAccountKeys.create ??

**Comment by sethvargo** [comment]
Yea - you'll need roles/serviceaccountadmin

**Comment by sethvargo** [comment]
@uasaigoli did that solve your issue?

**Comment by sethvargo** [comment]
Closing due to lack of response. Please let me know if I can help further!

**Comment by uasaigoli** [comment]
Apologies @sethvargo and I just returned from travel.

1 out 6 six issues has been resolved and I still see 5 errors outstanding. Not sure what the exact permission required. Really appreciate your pointers

oogle_project_service.service[1]: 1 error(s) occurred:

* google_project_service.service.1: Error enabling service: failed to issue request: googleapi: Error 403: The caller does not have permission, forbidden
* google_project_service.service[0]: 1 error(s) occurred:

* google_project_service.service.0: Error enabling service: failed to issue request: googleapi: Error 403: The caller does not have permission, forbidden
* google_project_service.service[4]: 1 error(s) occurred:

* google_project_service.service.4: Error enabling service: failed to issue request: googleapi: Error 403: The caller does not have permission, forbidden
* google_project_service.service[2]: 1 error(s) occurred:

* google_project_service.service.2: Error enabling service: failed to issue request: googleapi: Error 403: The caller does not have permission, forbidden
* google_project_service.service[3]: 1 error(s) occurred:

* google_project_service.service.3: Error enabling service: failed to issue request: googleapi: Error 403: The caller does not have permission, forbidden

**Comment by sethvargo** [comment]
Hi @uasaigoli 

Reopened, sorry about that, and welcome back 😄. Those are all the "same" error. It looks like the service account with which you are running Terraform does not have permission to enable services. Make sure your service account has the following permissions:

- `services.enable`
- `services.batchEnable`
- `services.disable`
- `services.get`
- `services.list`

Adding `roles/editor` should give you what you want. Otherwise, you can do something more fine-grained with `roles/serviceusage.serviceUsageViewer`, `roles/serviceusage.serviceUsageAdmin`, and `roles/servicemanagement.serviceConsumer`: https://cloud.google.com/service-usage/docs/access-control#roles

**Comment by uasaigoli** [comment]
Thanks. let me request to grant role `roles/editor` and see that resolves.

**Comment by uasaigoli** [comment]
great progress and thanks for your help @sethvargo. Now I have only one error. I would really appreciate your pointers.

* google_container_cluster.vault: 1 error(s) occurred:

* google_container_cluster.vault: googleapi: Error 400: master version "1.10.2-gke.3" is unsupported., badRequest

**Comment by sethvargo** [comment]
Ah yea - I updated the repo. Pull and try now

**Comment by uasaigoli** [comment]
Error: Error applying plan:

1 error(s) occurred:

* null_resource.apply: Error running command 'gcloud container clusters get-credentials "vault" --zone="us-east4-b" --project="myproject-name"
kubectl config set-context "gke_myproject-name_us-east4-b_vault"

**Comment by sethvargo** [comment]
Do you have gcloud installed? https://cloud.google.com/sdk/install

**Comment by uasaigoli** [comment]
>>gcloud --version
gives me the following:
Google Cloud SDK 209.0.0
bq 2.0.34
core 2018.07.16
gsutil 4.33

**Comment by sethvargo** [comment]
Hmm - it should be working then. Do you see any other error output?

**Comment by uasaigoli** [comment]
here is the log after the `terraform apply`

[https://gist.github.com/uasaigoli/4ab72020433c1cd8e92e44068c56f005](url)

**Comment by sethvargo** [comment]
Hmm weird. What operating system and version are you using?

**Comment by uasaigoli** [comment]
I am using mac locally for `terraform apply`; rest everything (cluster, vm) dictated by terraform, right?

**Comment by sethvargo** [comment]
Yea, that's weird. I just double-checked and it's working fine on my Mac. I'll need some more time to dig into this, sorry.

**Comment by uasaigoli** [comment]
meantime, can I destroy and apply again?

**Comment by sethvargo** [comment]
Yea - should be fine to do

**Comment by uasaigoli** [comment]
I did `terraform destroy`, then I did `terraform apply` and below is the log.

https://gist.github.com/uasaigoli/8bf7fa8bf1710f9730767202833470be

since I saw keyring related issue, I wanted cleanup and see any residuals from destroy and hence executed `terraform destroy`, but saw an error with destroy and please see the log

https://gist.github.com/uasaigoli/c4073be98776f371ddcfb5e476469054

**Comment by sethvargo** [comment]
What happens when you run:

```
kubectl config set-context "gke_myproject_us-east4-b_vault"
```

Manually?

**Comment by uasaigoli** [comment]
I get response `Killed: 9`

**Comment by sethvargo** [comment]
Hmm - that means something is going on with your `kubectl` command. What contexts do you have?

**Comment by uasaigoli** [comment]
I have reinstalled kubectl and looks like we are in good direction.

1.  tried `terraform apply` - it showed the error that can not create keyring due to existing keyring. 
2. I changed the keyring name to vault1 and did `terraform apply`, it gave following error:
* data.google_kms_secret.root-token: data.google_kms_secret.root-token: Error decrypting ciphertext: googleapi: Error 403: Permission 'cloudkms.cryptoKeyVersions.useToDecrypt' denied for resource 'projects/myproject/locations/us-east4/keyRings/vault1/cryptoKeys/vault-init'., forbidden

I wanted to start from 0, but when I `terraform destroy` it does not delete everything such as `vault`. Is there any way to start from 0?

**Comment by sethvargo** [comment]
Hey @uasaigoli 

When you `terraform apply`, it should be creating a new project, so it's okay to use the same key name. That permission error looks like you don't have permission to decrypt the proper permissions on the key.

**Comment by t898489** [comment]
We did not want to create a new project as we already have a project for prod and dev. We wanted to create vault resources for dev, for now, hence, I have modified the scripts that you have so that it will not create a new project instead it creates an existing project. please see my first post to see what I have changed to use existing dev project.

**Comment by uasaigoli** [comment]
We did not want to create a new project as we already have a project for prod and dev. We wanted to create vault resources for dev, for now, hence, I have modified the scripts that you have so that it will not create a new project instead it creates an existing project. please see my first post to see what I have changed to use existing dev project.

**Comment by sethvargo** [comment]
The Terraform configurations automatically create a service account with the correct permissions. If you're using your own service account, you'll need to add those permissions yourself manually or via the API.

**Comment by uasaigoli** [comment]
you helped us to resolve all permission issues; we use your script and all its defaults with following minor modifications.
1. we wanted to create all vault resources with our existing project. hence, updated .tf file to use the existing project.
2. when we applied that change, service account needed addition roles.permission and we resolved that with your help.

Issue are:
1. if we destroy, process does not clean up key and keyring.
2. when I apply after destroy, process failed because of existing vault keyring. not sure why it does not clean up; looks like there no way to delete keyring
3. since there is no way to clean up existing keyring, I have update .tf to have different name called 'vault1', but I get error while creating new keyring - I have pasted that error in previous post.

**Comment by sethvargo** [comment]
@uasaigoli 

> if we destroy, process does not clean up key and keyring.

does the service account **with which you're running Terraform** have permission to delete keys? (not the service account created by Terraform attached to the cluster, the service account that you're executing Terraform with)

> when I apply after destroy, process failed because of existing vault keyring. not sure why it does not clean up; looks like there no way to delete keyring

You can delete keys, but not keyrings, that's correct. This is why I create a new, dedicated project. You'll need to change the name of the keyring or use the `random_id` resource to create a new one (but watch your per-project quotas)

> since there is no way to clean up existing keyring, I have update .tf to have different name called 'vault1', but I get error while creating new keyring - I have pasted that error in previous post.

Use `random_id` (see the way I create the `google_project` in the original set of configurations). That being said, you will likely run out of quota if you create too many keys.

**Comment by uasaigoli** [comment]
I tried to re-run again by changing key and keyring and it gave me following error

 google_storage_bucket.vault: 1 error(s) occurred:

* google_storage_bucket.vault: googleapi: Error 409: You already own this bucket. Please select another name., conflict

then, I changed google_storage_bucket.vault to google_storage_bucket.vault2 and it gave similar error with google_storage_bucket.vault2.

**Comment by sethvargo** [comment]
You'll need to change the name of the storage bucket. Storage bucket names must be globally unique. These configurations aren't really designed to be modified in the way you're trying to

**Comment by uasaigoli** [comment]
we have created new project and did minor changes to the script to have all vault resources to create under existing project, instead of creating new project. It all went well and thank so much.
