### ISSUE TITLE
Error when importing route resources 

### ISSUE THREAD

**Issue by vdamianchicon** [sethvargo/vault-on-gke#40]
**What did you expect to happen?**

```
$ terraform import google_compute_route.default-route-.. default-route-..
```

Import succeeds

**What actually happened?**
Import Fails

**Output**

```
Error: Provider "kubernetes" depends on non-var "google_container_cluster.vault.0/google_container_cluster.vault.N". Providers for import can currently
only depend on variables or must be hardcoded. You can stop import
from loading configurations by specifying `-config=""`.
```

**Comment by vdamianchicon** [comment]
Is this related to this limitation on the kubernetes/import provider?
The only limitation Terraform has when reading the configuration files is that the import provider configurations must not depend on non-variable inputs. For example, a provider configuration cannot depend on a data source.
https://www.terraform.io/docs/commands/import.html#provider-configuration
https://github.com/hashicorp/terraform/issues/17847

**Comment by sethvargo** [comment]
This is a Terraform limitation. It has nothing to do with these configs or the Kubernetes or Google providers. There's no way to update the config to not have such a dependency (the cluster must be created before you can apply configs to it).
