### ISSUE TITLE
vault-nat-external-0, and vault-nat-external-1

### ISSUE THREAD

**Issue by vdamianchicon** [sethvargo/vault-on-gke#41]
**Question**
What is your question?
why/how are the External IP addresses vault-nat-external-0 and vault-nat-external-1 are created?
Don't see the terrafrorm code that does that
They are not attached to anything
**Considerations**
Are there any other considerations?

**Comment by sethvargo** [comment]
They are used [here](https://github.com/sethvargo/vault-on-gke/blob/master/terraform/gcp.tf#L203-L204). I think there's a bug in the UI where they show as "unused" but they are for the NAT gateway.

**Comment by vdamianchicon** [comment]
Thank you. Created this issue https://issuetracker.google.com/issues/126874323
