### ISSUE TITLE
Node Pools settings considerations

### ISSUE THREAD

**Issue by vdamianchicon** [sethvargo/vault-on-gke#42]
**Question**
The current configuration has the following settings. Is there a performance or security concern driving these setting?

```
Automatic node upgrades	Disabled
Automatic node repair	Disabled
Autoscaling	Off
Preemptible nodes	Disabled
```

**Comment by sethvargo** [comment]
- You can turn on auto-upgrades and that's probably more secure. Some users had concerns about auto-upgrading and compatibility, so it's off by default. It's also not available on alpha clusters, and many users are using alpha clusters.
- Autoscaling/auto-repair won't help or hurt - only one Vault node will service requests at a time
- [Preemptible VMs](https://cloud.google.com/kubernetes-engine/docs/how-to/preemptible-vms) last no longer than 24 hours and can be terminated at any time
