### ISSUE TITLE
Enable transit engine on Vault

### ISSUE THREAD

**Issue by ziyadparekh** [sethvargo/vault-on-gke#43]
**Question**
What is your question?
What would be the right place to enable the transit secrets engine in the configuration files? Or would it be better to add the command in the vault-init docker image?

**Comment by sethvargo** [comment]
This is a more general question of "how do I preconfigure Vault" for which there's no answer today. I [wrote about this](https://www.hashicorp.com/blog/codifying-vault-policies-and-configuration) in my previous role, but I don't think there's a good solution yet.
