### ISSUE TITLE
Connect to existing secrets in GCS from new Vault GKE cluster

### ISSUE THREAD

**Issue by bryan831** [sethvargo/vault-on-gke#49]
**Question**
What are the modifications necessary to connect to existing secrets in GCS from a new Vault cluster in GKE?

**Considerations**
n.a

Hi guys, after trying this demo and playing around with Vault, my team is keen on implementing Vault for some of our systems. 

One last concern I was tasked to investigate -- is it possible to connect to existing secrets in GCS in the event of an unintended loss of Vault cluster (e.g. human accidentally deleted Vault cluster in GKE, other problem with Vault cluster)? 
If so, what are the necessary modifications required?

_I tried several modifications (the KMS keys, GCS bucket name) to the terraform files to achieve this. The best I was able to achieve was a newly created Vault cluster, and `terraform apply` returned the same root token as the previous cluster. However, in Vault UI, I was unable to login with this same root token._

Thanks!

**Comment by sethvargo** [comment]
Hi @bryan831 

When you say "connect to existing secrets in GCS" which of the following do you mean:

1. An existing GCS bucket that Vault was using to store data
2. An existing GCS bucket where you put your own data

Vault's storage backend is pluggable, if you spin up vault-cluster-1 against GCS bucket foo, tear it down, and then spin up vault-cluster-2 against the _same_ GCS bucket, it will have the same secrets, same unseal keys, same root token, etc.

Does that answer your question? Sorry I'm not sure I completely understand the issue.

**Comment by bryan831** [comment]
Hi @sethvargo thanks for your reply.
I am referring to 1, exactly the scenario you have mentioned.

I'm having difficulty modifying the demo `terraform` files to get it to spin up a new Vault cluster against existing Vault GCS secrets bucket.

Could you let me know the _only_ fields I have to change in the `terraform` files to achieve this?  
I think I might have modified more fields than necessary, or missed out some, that is why I cannot login to my new Vault cluster.

Thank you very much

**Comment by sethvargo** [comment]
- Delete [this](https://github.com/sethvargo/vault-on-gke/blob/41f118c8ffbc2eb9cbe6a8d5396211bdcc8b2737/terraform/gcp.tf#L81-L103)
- Change [this](https://github.com/sethvargo/vault-on-gke/blob/41f118c8ffbc2eb9cbe6a8d5396211bdcc8b2737/terraform/gcp.tf#L108) to the name of your bucket
- Change [this](https://github.com/sethvargo/vault-on-gke/blob/41f118c8ffbc2eb9cbe6a8d5396211bdcc8b2737/terraform/k8s.tf#L45) to the name of your bucket
- Change [this](https://github.com/sethvargo/vault-on-gke/blob/41f118c8ffbc2eb9cbe6a8d5396211bdcc8b2737/terraform/k8s.tf#L96) to the name of your bucket
