### ISSUE TITLE
Upgrade to Terraform 0.12

### ISSUE THREAD

**Issue by sethvargo** [sethvargo/vault-on-gke#55]
We need to update to Terraform 0.12, but there's still many users running 0.11. We will wait until ~0.12.5 to upgrade and release as a new tag indicating a breaking change.

**Comment by sethvargo** [comment]
If you absolutely need this today, you can use the `sethvargo/12` branch in this repo.

**Comment by developmentsystems** [comment]
No worries, thanks Seth.

**Comment by sethvargo** [comment]
In master now
