### ISSUE TITLE
Vault metrics in to Stackdriver

### ISSUE THREAD

**Issue by divyesh-bg** [sethvargo/vault-on-gke#59]
**Question**
I have been trying to figure out the best way to get Vault custom metrics into stackdriver. The stackdriver docs don't quite help with any sort of examples on sending out custom (application specific) metrics in to stackdriver. Is it possible for you to provide any example or add support for vault metrics to go to stackdriver here?

The logs are going to stackdriver already.

**Considerations**

**Comment by sethvargo** [comment]
https://github.com/hashicorp/vault/pull/6957 has been over for about a month for merge.

**Comment by divyesh-bg** [comment]
@sethvargo  thanks for the pointer! Looks like it will be a wait until it merges and a new release has it available.
