### ISSUE TITLE
How to split the work into GCP infrastructure and a vault helm chart?

### ISSUE THREAD

**Issue by victorhdamian** [sethvargo/vault-on-gke#62]
**Question**
How to split the work into GCP infrastructure and a vault helm chart?
Any thoughts?

**Considerations**
I have split the work into a gcp component managed by terraform and a vault chart which takes the value inputs from the outputs of the terraform run.

I have run into an issue unsealing.
because the root_key is not being generated
if I dont use the k8s.tf component of the terraform and move that part to the custom helm chart I get 

```
Error: HTTP request error. Response code: 404
  on k8s.tf line 47, in data "http" "keys":
  47: data "http" "keys" {
```

Because the root-token.enc has not being generated. During the terraform run

**Comment by sethvargo** [comment]
You can delete the entire k8s.tf file if you're not going to have Terraform deploy Vault onto the cluster.

**Comment by victorhdamian** [comment]
When in the process does the root-token.enc gets created?

**Comment by sethvargo** [comment]
The `vault-init` container creates it

**Comment by victorhdamian** [comment]
Thank you Seth!!
