### ISSUE TITLE
Terraform apply issue

### ISSUE THREAD

**Issue by bgdanix** [sethvargo/vault-on-gke#64]
**What did you expect to happen?**
Terraform apply should run without errors

**What actually happened?**
Multiple errors:
Invalid template interpolation value
kubernetes_dashboard": [REMOVED]

**Fix**
Modify "null_resource" "apply" in k8s.tf and use "${google_container_cluster.vault.location}" instead of region since there isn't region in GKE resource
Modify gcp.tf and remove the addon for kubernetes_dashboard

**Comment by sethvargo** [comment]
Fixed in c98b3f4. Thanks!
