### ISSUE TITLE
terraform apply didn't work

### ISSUE THREAD

**Issue by mnothic** [sethvargo/vault-on-gke#68]
**What did you expect to happen?**
make the terraform apply in terraform directory to deploy vault on gke but fails on the kubernetes privider.

**What actually happened?**
checkout repository add terraform.tfvars with  cloud values
terraform.tfvars:
billing_account = "XXXXXX-XXXXXX-XXXXXX"
project = "vault"
org_id = 1111111111111111
region = "europe-west1"

**Output**
```
 terraform version
Terraform v0.12.20
+ provider.google v3.8.0
+ provider.google-beta v3.8.0
+ provider.kubernetes v1.11.0
+ provider.random v2.2.1
+ provider.tls v2.1.1
terraform init
Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.google-beta: version = "~> 3.8"
* provider.kubernetes: version = "~> 1.11"
* provider.random: version = "~> 2.2"
* provider.tls: version = "~> 2.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

terraform apply
data.google_client_config.current: Refreshing state...
data.google_project.vault: Refreshing state...
data.google_container_engine_versions.versions: Refreshing state...

Error: Failed to initialize config: invalid configuration: no configuration has been provided

  on k8s.tf line 6, in provider "kubernetes":
   6: provider "kubernetes" {

```

**Comment by sethvargo** [comment]
This appears to be a bug in the Kubernetes provider? https://github.com/terraform-providers/terraform-provider-kubernetes/issues/521

**Comment by ArkeologeN** [comment]
I did encounter the same problem but for someone coming here again, please try to pin `kubernetes` version to `1.10.0`

full example:

```
provider "kubernetes" {
  version          = "1.10.0"
  load_config_file = false
  host             = google_container_cluster.vault.endpoint

  cluster_ca_certificate = base64decode(
    google_container_cluster.vault.master_auth[0].cluster_ca_certificate,
  )
  token = data.google_client_config.current.access_token
}
```

**Comment by sethvargo** [comment]
Yes, please pin to an older version and also add your experience to the cross-referenced issue in the Kubernetes provider please.

**Comment by mnothic** [comment]
Thanks guys I already did a smooth deployment!

**Comment by pdecat** [comment]
Hi,

this was caused by a change in behavior in the terraform kubernetes provider v1.11.0 (see https://github.com/terraform-providers/terraform-provider-kubernetes/pull/690) and will be resolved by https://github.com/terraform-providers/terraform-provider-kubernetes/pull/767.

For the time being, pinning to v1.10.0 as suggested by https://github.com/sethvargo/vault-on-gke/issues/68#issuecomment-585773137 is the recommended work-around.

**Comment by pdecat** [comment]
Hi, this should be fixed by v1.11.1 of the terraform provider for kubernetes.

https://github.com/terraform-providers/terraform-provider-kubernetes/blob/v1.11.1/CHANGELOG.md#1111-february-28-2020

**Comment by mnothic** [comment]
I had to pin to 1.9.0 cuz version 1.10.0 can't detect google_client_config neither!

**Comment by pdecat** [comment]
@mnothic did you try v1.11.1?

**Comment by mnothic** [comment]
tested and working with v1.11.1
