### ISSUE TITLE
Error: Error waiting for creating GKE cluster: All cluster resources were brought up, but: 3 nodes out of 3 are unhealthy.    on gcp.tf line 239, in resource "google_container_cluster" "vault":

### ISSUE THREAD

**Issue by Reifier** [sethvargo/vault-on-gke#69]
**What did you expect to happen?**
Describe what you expected to happen here.

Expected cluster to come up.

**What actually happened?**

Describe what actually happened here.

Cluster creation timed out after 30 minutes

**Output**
```text
Error: Error waiting for creating GKE cluster: All cluster resources were brought up, but: 3 nodes out of 3 are unhealthy.

  on gcp.tf line 239, in resource "google_container_cluster" "vault":
 239: resource "google_container_cluster" "vault" {

```

**Additional context**
I've used this repo in the beginning of the week and everything was working fine, mid week porject/cluster creation started to fail inconsistently. Now the cluster never comes up. I've thought this might be related to terraform/gcp provider/k8s master versions tried changing them to the latest and past multiple times. Tried adding extra oauth scopes on the cluster. Tried giving service account full editor permissions for gcp instances. Nothing works. Last screenshot is the error message after timeout. GCP/GKE stackdriver logs don't produce any useful information.
<img width="1291" alt="Screen Shot 2020-02-26 at 11 10 37 AM" src="https://user-images.githubusercontent.com/8810911/75578951-af4d9180-5a19-11ea-8d00-3e277bce6107.png">
<img width="415" alt="Screen Shot 2020-02-26 at 11 17 39 AM" src="https://user-images.githubusercontent.com/8810911/75578957-b1afeb80-5a19-11ea-9970-bf2f904f75bd.png">

**Comment by sethvargo** [comment]
Can you share the Vault logs?

**Comment by Reifier** [comment]
Vault never comes up because cluster creation fails on health check stage (1st screenshot above). This is the relevant instance log:
```
Kubernetes Engine API
CreateCluster
us-east4:vault
DEADLINE_EXCEEDED
Expand all | Collapse all{
insertId: "6dsyeqd97js"
logName: "projects/vault-8c1cdccc66b6e942/logs/cloudaudit.googleapis.com%2Factivity"
operation: {
id: "operation-1582756697853-0fad977b"
last: true
producer: "container.googleapis.com"
}
protoPayload: {
@type: "type.googleapis.com/google.cloud.audit.AuditLog"
methodName: "google.container.v1beta1.ClusterManager.CreateCluster"
requestMetadata: {
destinationAttributes: {…}
requestAttributes: {…}
}
resourceLocation: {
currentLocations: [1]
}
resourceName: "projects/vault-8c1cdccc66b6e942/locations/us-east4/clusters/vault"
serviceName: "container.googleapis.com"
status: {
code: 4
message: "DEADLINE_EXCEEDED"
}
}
receiveTimestamp: "2020-02-26T23:08:15.286593384Z"
resource: {
labels: {…}
type: "gke_cluster"
}
severity: "ERROR"
timestamp: "2020-02-26T23:08:15.072260588Z"
}
```

**Comment by sethvargo** [comment]
That issue appears to be coming from GKE directly, not related to this repo specifically. Are you able to create a GKE cluster successfully? (i.e. using the Cloud Console)

**Comment by Reifier** [comment]
Yes. Cluster creation through both console and gcloud command works.

**Comment by Reifier** [comment]
Closing as I can no longer reproduce.
