### ISSUE TITLE
How would you go to then use the vault provider of terraform

### ISSUE THREAD

**Issue by loispostula** [sethvargo/vault-on-gke#7]
I don't like the idea to commit the `ca.pem` `vault.key` `vault.pem` file to the repo, and can't manage to use `${data.google_kms_secret.root-token.plaintext}` as a token

**Comment by sethvargo** [comment]
`ca.pem` is a _public_ key, so you can commit it if you'd like. You don't need `vault.key` or `vault.pem` to talk to the server unless you're enabling mTLS. 

Can you share more about what you mean that you can't get the plaintext as the token? Are you getting an error? I need logs and more information.
