### ISSUE TITLE
http_proxy breaks vault-init

### ISSUE THREAD

**Issue by Reifier** [sethvargo/vault-on-gke#70]
**What did you expect to happen?**
I'd like to use k8s auth method with vault and a private k8s master on gke. However, private master endpoint requires an http(s) proxy. I expect to edit the terraform file with ss env variables, put the http_proxy env var into vault container and have it run as normal.
```
          env {
            name  = "HTTP_PROXY"
            value = "http://10.48.24.61:8118"
          }
```

**What actually happened?**
Stateful set fails to start

**Output**
```text
kubectl logs vault-0 vault-init
2020/03/06 01:23:15 Starting the vault-init service...
2020/03/06 01:23:15 Head http://127.0.0.1:8200/v1/sys/health: dial tcp 127.0.0.1:8200: connect: connection refused
2020/03/06 01:23:25 Head http://127.0.0.1:8200/v1/sys/health: dial tcp 127.0.0.1:8200: connect: connection refused
```

**Additional context**
Note that I don't even modify vault-init. Only vault container env vars. Nevertheless init phase never finishes.

**Comment by sethvargo** [comment]
The vault-init container does not seem to support proxy configuration. Please open an upstream issue.

**Comment by sethvargo** [comment]
The vault-init container does not seem to support proxy configuration. Please open an upstream issue.
