### ISSUE TITLE
How can enable injector in this code?

### ISSUE THREAD

**Issue by SrikantPatil88** [sethvargo/vault-on-gke#77]
Hi,

Vault server 1.3.5 is running on GKE and  We want the vault-k8s injector capability to talk to this vault server.

I just wanted to understand how we can enable injector in existing Vault server? Do we need or K8s can talk to Vault server and fetch secrets from yaml file.

**Comment by aluis-ac** [comment]
Hello there,

Same doubt, the setup is running smoothly but I need to add injetor... any clue? Thanks

**Comment by aluis-ac** [comment]
@SrikantPatil88  My alternative to get around that we're to get all inspector resources from (https://github.com/hashicorp/vault-helm) wich was:

injector-clusterrole.yaml / injector-clusterrolebinding.yaml / injector-deployment.yaml / injector-mutating-webhook.yaml / injector-network-policy.yaml / injector-service.yaml / injector-serviceaccount.yaml I do edited that as I was not going to use helm and then applied among the same TF module as following:

resource "null_resource" "vault-agent-injector" {
  provisioner "local-exec" {
    command = "kubectl apply -f ${path.module}/injector-templates/"
  }
}

Nothing fancy but works great,  hope it can help somehow.

**Comment by SrikantPatil88** [comment]
Thanks @aluis-ac , Really it helped me.

**Comment by agates4** [comment]
@SrikantPatil88 thank you for posting this issue.

can you paste the output of your modification?

**Comment by agates4** [comment]
https://github.com/hashicorp/vault-k8s/issues/15#issuecomment-591749580
this is a great guide to installing the injector manually. I will see if I can get this into terraform steps

**Comment by agates4** [comment]
ok I got this into terraform steps
https://github.com/sethvargo/vault-on-gke/pull/98
waiting on @sethvargo for a review
