### ISSUE TITLE
how to access the vault internally in other project ?

### ISSUE THREAD

**Issue by uasaigoli** [sethvargo/vault-on-gke#8]
I have created vault in a separate project. 
Looks like default script creates load balanced url/ip to vault cluster, which can be accessed over internet. We do not want to expose vault url to outside and want access within firewall  where all of our services are in different project housed.

vault_project.
services_project -> services housed in this project need access the vaults with firewall.

questions:
1. what changes do I need to make to keep the vault cluster internally accessible?
2. if I make any of changes for #1, will it cause any issues when `apply` changes terraform?

**Comment by sethvargo** [comment]
Hi @uasaigoli 

This setup is a bit out of scope for the goals of this project. In short, you would need to:

1. Create a dedicated network and subnetwork
1. Attached a firewall to that network
1. Setup firewall rules to allow/deny traffic

Any changes you make via the web console, command line, or other tools will cause Terraform to detect drift and thus try to resolve that diff.
