### ISSUE TITLE
Enabling HA causes thousands of lock files in the storage bucket

### ISSUE THREAD

**Issue by scarolan** [sethvargo/vault-on-gke#84]
**What did you expect to happen?**
Follow the readme, run `terraform apply` and Vault runs without creating too many lock files.

**What actually happened?**
When you run the terraform with `ha_enabled = "true"`, a new lock file is created in the core/ path every few seconds. Here are a few examples of what they look like:

```
gs://stitch-vault-vault-storage/core/lock#1598906934814007
gs://stitch-vault-vault-storage/core/lock#1598906939814838
gs://stitch-vault-vault-storage/core/lock#1598906944820242
```

I discovered this after letting the cluster run for a few days and then trying to `terraform destroy`. The destroy was hanging because there were simply too many files in the bucket.

Switching `ha_enabled` to false resolves the problem with too many files.

**Additional context**
I tested this with both Vault 1.2.1 and 1.5.2 and got the same result with the lock# files.

**Comment by sethvargo** [comment]
Those aren't files, those are versions of the same file. This makes sense as Vault "touches" the lock file every 15s. I recommend creating a bucket lifecycle policy to cleanup old object versioning or disable versioning altogether.

**Comment by scarolan** [comment]
Thanks for clarifying that, @sethvargo. I see that you already have `num_newer_versions = 1`. I'll experiment with the lifecycle settings and see if i can find a fix.

**Comment by scarolan** [comment]
It seems to not honor the num_newer_versions setting.  I changed this to 5 but it still creates a new one every 15 seconds. Going to disable versioning on my bucket and make sure we take regular backups.
