### ISSUE TITLE
Terraform module

### ISSUE THREAD

**Issue by ussuritiger** [sethvargo/vault-on-gke#87]
**Question**
Can this tutorial be wrapped up into the Terraform module and published to registry?

**Considerations**
There is already a module (https://github.com/terraform-google-modules/terraform-google-vault) to deploy Vault on GCE. Would be nice to have a module in Terraform registry based on this tutorial to deploy Vault on GKE.

**Comment by sethvargo** [comment]
You can just point to this repo as the source:

```terraform
module "..." {
  source = "github.com/sethvargo/vault-on-gke"
}
```
