### ISSUE TITLE
Enterprise Vault on GKE with Consul backend

### ISSUE THREAD

**Issue by SrikantPatil88** [sethvargo/vault-on-gke#89]
Hi Folks,

Sorry to asking a different question but just I am curios to understand possibility,

I have installed the opensource vault on GKE with GCS banckend using sethvergo/vault-on-gke terraform code and that is working awesome but we want HA and DR which is not possible with opersource.

We have purchased enterprise vault but I am not able to find any reference of terraform code to deploy enterprise vault on GKE with Consule backend.

 Can anyone please help me to understand, Whether it is possible to deploy enterprise vault on GKE with consul backend using terraform code?
if yes, then can you please give me the reference or let me know how I can do it?
if no, The is there any other way except manual installation?

Thanks in advance

**Comment by SrikantPatil88** [comment]
Looks like nobody is using enterprise or I am asking the question in wrong group.

**Comment by sethvargo** [comment]
This is a personal repo and project. If you purchased Vault Enterprise, you have a paid support plan from HashiCorp - they should be able to help.
